### ISSUE TITLE
Load configuration at run-time as opposed to build-time

### ISSUE THREAD

**Issue by MarkBonner** [sourcenetwork/ng-oidc-client#23] opened 2020-01-20 13:13 UTC
**Is your feature request related to a problem? Please describe.**

We are currently loading our configuration from a local asset. When deploying the application we can change the configuration before building and deploying within our CI pipeline. However, the build for our staging and production servers needs to be identical, so the configuration needs loading at run-time.

**Describe the solution you'd like**

Modify the library to support the loading of the configuration at run-time.

**Describe alternatives you've considered**

Loading the configuration from an external service, then using the Angular APP_INITIALIZER to inhibit the initialisation process until loaded. There have been problems with this approach, so currently isn't working.

**Additional context**

Looks as if the ng8 branch is supporting this feature? Will this be released and if so when?

**Comment by david-on-github** [comment] 2020-02-04 22:41
Hi Mark,

I just published the branch. Try the alternative configuration method eg. [here](https://github.com/sourcenetwork/ng-oidc-client/blob/master/src/app/app.module.ts#L72). 

Let me know if you have any issues.

**Comment by MarkBonner** [comment] 2020-02-05 15:08
Many Thanks!!

**Comment by dtaylor84** [comment] 2020-02-06 15:11
@david-on-github I'm trying to use this but getting

`Warning: Can't resolve all parameters for OidcFacade in .../node_modules/ng-oidc-client/ng-oidc-client.d.ts: (?, [object Object], [object Object]). This will become an error in Angular v6.x`

Which seems vaguely similar to #2 -- and I notice that a barrel import sneaked into the latest commit here (although I'm not sure it's the cause of the problem).
https://github.com/sourcenetwork/ng-oidc-client/blob/e4db2a1c7301cf1c2afeb854cbc69b3c5a245504/projects/ng-oidc-client/src/public_api.ts#L8

**Comment by david-on-github** [comment] 2020-02-06 15:20
@dtaylor84 

Are you using Angular <= 7? There is a backwards compatibility issue with injection tokens.

**Comment by dtaylor84** [comment] 2020-02-06 15:35
@david-on-github

No, I'm using Angular 8

**Comment by david-on-github** [comment] 2020-02-06 16:14
@dtaylor84  
Thanks, patched a fix. Let me know how it works.

**Comment by dtaylor84** [comment] 2020-02-06 16:44
@david-on-github 

I guess you've already noticed a problem, as your comment has disappeared, but v2.0.2 changes the warning into an error.

(I should have mentioned the warning/error only appears when using --prod to build with the AOT compiler.)

**Comment by david-on-github** [comment] 2020-02-06 16:58
@dtaylor84 
Yup, I saw, Thanks. 
Should be fixed now. Let me know.

**Comment by dtaylor84** [comment] 2020-02-07 08:38
@david-on-github 

It's working fine now -- thanks for the quick fix!

**Closed** 2020-02-10 22:06 UTC
